- name: Setup Nginx
  hosts: all
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 8080
  become: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Copy index.html file
      ansible.builtin.copy:
        src: files/index.html.j2
        dest: "{{root_dir}}/index.html"

    - name: Copy nginx.conf file
      ansible.builtin.copy:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: "restart nginx"
    
    - name: Install cowsay
      ansible.builtin.package:
        name: cowsay
        state: present

    - name: Run cowsay command
      ansible.builtin.shell:
        cmd: cowsay "This is server {{ inventory_hostname }}!"
        register: cowsay_result

  handlers:
    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
